apps/services/urls.py
from django.conf.urls import include
from django.urls import path
from rest_framework import routers

from apps.services.views import ServiceCreate, ServiceTypeViewSet, ServiceViewSet

router = routers.SimpleRouter()

router.register(r'service-type', ServiceTypeViewSet, basename='service_type')
router.register(r'api', ServiceViewSet, basename='service')

urlpatterns = [
    path('', include(router.urls)),
    path('', ServiceCreate.as_view(), name='order_services'),
]

panda/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', include('apps.about.urls')),
    path('account/', include('apps.accounts.urls')),
    path('employees/', include('apps.employees.urls')),
    path('frequently_asked_questions/', include('apps.frequently_asked_questions.urls')),
    path('services/', include('apps.services.urls')),
    path('', include('apps.main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/services/models.py
from django.contrib.auth.models import User
from django.db import models


class Specialists(models.Model):
    first_name = models.CharField(max_length=50, verbose_name='Имя')
    last_name = models.CharField(max_length=50, verbose_name='Фамилия')
    email = models.EmailField(verbose_name='Почта', default='arefyev.sergey@mail.ru')
    post = models.CharField(max_length=256, verbose_name='Должность')

    def __str__(self):
        return f'{self.last_name} {self.first_name}'

    class Meta:
        verbose_name = 'Специалист'
        verbose_name_plural = 'Специалисты'


class PromoCode(models.Model):
    code = models.CharField(unique=True, max_length=255, verbose_name='Код')
    user = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = 'Промо-код'
        verbose_name_plural = 'Промо-коды'


class Website(models.Model):
    code = models.CharField(unique=True, max_length=255, verbose_name='Код',
                            help_text='Уникальный код вебсайта. Например "vk"')
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Сайт'
        verbose_name_plural = 'Сайты'


class ServiceType(models.Model):
    name = models.CharField(max_length=255)
    website = models.ForeignKey(Website, on_delete=models.PROTECT, verbose_name='Вебсайт')
    price = models.DecimalField(max_digits=15, decimal_places=2, verbose_name='Цена',
                                help_text='Стоимость одной единицы')

    def __str__(self):
        return f'{self.website.name} {self.name}'

    class Meta:
        verbose_name = 'Тип услуги'
        verbose_name_plural = 'Типы услуг'


class Services(models.Model):
    website = models.ForeignKey(Website, on_delete=models.PROTECT, verbose_name='Вебсайт')
    type = models.ManyToManyField(ServiceType, verbose_name='Тип услуги')
    specialist = models.ForeignKey(Specialists, on_delete=models.PROTECT, verbose_name='Специалист')
    count = models.IntegerField(verbose_name='Количество услуг')
    promo_code = models.CharField(max_length=100, blank=False, verbose_name='Промо-код')
    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='Пользователь')

    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'

apps/services/forms.py
from django import forms
from django.forms.utils import ErrorList

from apps.services.models import Services, PromoCode


class ServiceForm(forms.ModelForm):
    promo_code = forms.CharField(max_length=100, required=False)

    error_messages = {
        'not_prom_code': 'Нет такого промо-кода',
        'user_not_register': 'Заказать услуги могут только авторизованные пользователи'
    }

    class Meta:
        model = Services
        fields = ('website', 'type', 'specialist', 'count', 'promo_code',)

    def clean_promo_code(self):
        promo_code = self.cleaned_data['promo_code']

        if promo_code and promo_code not in PromoCode.objects.values_list('code', flat=True).all():
            self._errors["promo_code"] = ErrorList([
                self.error_messages['not_prom_code']
            ])

        return promo_code

apps/services/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.db.models import Sum
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import CreateView
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import viewsets, mixins
from rest_framework.decorators import action
from rest_framework.response import Response

from apps.about.models import Contacts
from apps.services.forms import ServiceForm
from apps.services.models import Services, ServiceType
from apps.services.serializers import ServiceTypeSerializer, ServicesSerializer


class ServiceCreate(CreateView):
    model = Services
    form_class = ServiceForm
    template_name = 'services/service_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['contact'] = Contacts.objects.all()[0]
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        form.save_m2m()
        # self._send_email_specialist(self.object)
        return HttpResponseRedirect(self.get_success_url())

    def _send_email_specialist(self, services: Services):
        subject = f'Заказ услуги'
        message = f'Заказана услуга от {services.user.profile.fio}.\n\n' \
                  f'Заказ для сайта {services.website.name} по услугам {", ".join(services.type.all().values_list("name", flat=True))}\n' \
                  f'На общую сумму {self._result_sum(services)} ₽'
        send_mail(subject, message, settings.EMAIL_HOST_USER, [services.specialist.email], fail_silently=False)

    def _result_sum(self, services: Services):
        count_services = services.count
        all_price = services.type.all().aggregate(all_price=Sum('price'))
        return round(all_price.get('all_price') * count_services, 2)

    def get_success_url(self):
        return reverse('order_services')


class ServiceTypeViewSet(mixins.ListModelMixin,
                         viewsets.GenericViewSet):
    queryset = ServiceType.objects.all()
    serializer_class = ServiceTypeSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['name', 'website']


class ServiceViewSet(mixins.ListModelMixin,
                     viewsets.GenericViewSet):
    queryset = Services.objects.all()
    serializer_class = ServicesSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['id']

    @action(detail=False, methods=['get'], url_path='result_sum', url_name='result_sum')
    def result_sum_services(self, request):
        params = request.query_params
        params_type = [int(i) for i in params.getlist('type[]')]
        params_count = int(params.get('count'))
        all_price = ServiceType.objects.filter(id__in=params_type).aggregate(all_price=Sum('price'))
        return Response(all_price.get('all_price') * params_count)

apps/services/templates/services/service_create.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'services/css/service_create.css' %}">
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'services/js/service_create.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="service_message">
        {% if form.errors %}
            <b style="color:yellow;opacity:0.8">
                {% for key, value in form.errors.items %}
                    {% for error_text in value.data %}
                        {{ error_text }}<br>
                    {% endfor %}
                {% endfor %}
            </b>
        {% else %}
            Закажите услугу - это просто!
        {% endif %}
    </div>
    <form method="post">
        {% csrf_token %}
        <h1>Заказать услугу</h1>
        <div class="mx-3 label">Вебсайт:</div>
        <div class="d-flex justify-content-center mb-3">
            <select id="id_website" name="website" class="col-10" required>
                {% for id, name in form.website.field.choices %}
                    <option value="{{ id }}">{{ name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="mx-3 label">Тип услуги:</div>
        <div class="d-flex justify-content-center mb-3">
            <select id="id_type" name="type" class="col-10" required multiple></select>
        </div>
        <div class="mx-3 list-service">
            <a href="{% static 'docs/list_service.pdf' %}" target="_blank">
                Посмотреть полный список услуг
            </a>
        </div>
        <div class="mx-3 label">Специалист:</div>
        <div class="d-flex justify-content-center mb-3">
            <select id="id_specialist" name="specialist" class="col-10" required>
                {% for id, name in form.specialist.field.choices %}
                    <option value="{{ id }}">{{ name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="mx-3 label">Количество:</div>
        <div class="d-flex justify-content-center mb-3">
            <input id="id_count" class="col-10" placeholder="Количество" name="count" required>
        </div>

        <div class="mx-3 label">Промо-код:</div>
        <div class="d-flex justify-content-center mb-3">
            <input id="id_promo_code" class="col-10" placeholder="Промо-код" name="promo_code">
        </div>

        <div class="mx-3 label label_itog">Итог:<span class="itog">0 &#8381;</span></div>

        <div class="d-flex justify-content-center">
            <button id="service_order" class="button_profile_form mt-4 mb-2 col-6" type="submit">Заказать услугу</button>
        </div>
    </form>
{% endblock %}

apps/services/templates/services/services.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}